export const languageArray = [
    "aa",
    "ab",
    "af",
    "am",
    "ar",
    "as",
    "ay",
    "az",
    "ba",
    "be",
    "bg",
    "bh",
    "bi",
    "bn",
    "bo",
    "br",
    "ca",
    "co",
    "cs",
    "cy",
    "da",
    "de",
    "dz",
    "el",
    "en",
    "eo",
    "es",
    "et",
    "eu",
    "fa",
    "fi",
    "fj",
    "fo",
    "fr",
    "fy",
    "ga",
    "gd",
    "gl",
    "gn",
    "gu",
    "ha",
    "he",
    "hi",
    "hr",
    "hu",
    "hy",
    "ia",
    "id",
    "ie",
    "ik",
    "in",
    "is",
    "it",
    "iw",
    "ja",
    "ji",
    "jw",
    "ka",
    "kk",
    "kl",
    "km",
    "kn",
    "ko",
    "ks",
    "ku",
    "ky",
    "kz",
    "la",
    "ln",
    "lo",
    "ls",
    "lt",
    "lv",
    "mg",
    "mi",
    "mk",
    "ml",
    "mn",
    "mo",
    "mr",
    "ms",
    "mt",
    "my",
    "na",
    "ne",
    "nl",
    "no",
    "oc",
    "om",
    "or",
    "pa",
    "pl",
    "ps",
    "pt",
    "qu",
    "rm",
    "rn",
    "ro",
    "ru",
    "rw",
    "sa",
    "sb",
    "sd",
    "sg",
    "sh",
    "si",
    "sk",
    "sl",
    "sm",
    "sn",
    "so",
    "sq",
    "sr",
    "ss",
    "st",
    "su",
    "sv",
    "sw",
    "sx",
    "ta",
    "te",
    "tg",
    "th",
    "ti",
    "tk",
    "tl",
    "tn",
    "to",
    "tr",
    "ts",
    "tt",
    "tw",
    "uk",
    "ur",
    "us",
    "uz",
    "vi",
    "vo",
    "wo",
    "xh",
    "yi",
    "yo",
    "zh",
    "zu",
]

export const languageISO = {
    "aa":    "Afar",
    "ab":    "Abkhazian",
    "af":    "Afrikaans",
    "am":    "Amharic",
    "ar":    "Arabic",
    "as":    "Assamese",
    "ay":    "Aymara",
    "az":    "Azeri",
    "ba":    "Bashkir",
    "be":    "Belarusian",
    "bg":    "Bulgarian",
    "bh":    "Bihari",
    "bi":    "Bislama",
    "bn":    "Bengali",
    "bo":    "Tibetan",
    "br":    "Breton",
    "ca":    "Catalan",
    "co":    "Corsican",
    "cs":    "Czech",
    "cy":    "Welsh",
    "da":    "Danish",
    "de":    "German",
    "dz":    "Bhutani",
    "el":    "Greek",
    "en":    "English",
    "eo":    "Esperanto",
    "es":    "Spanish",
    "et":    "Estonian",
    "eu":    "Basque",
    "fa":    "Farsi",
    "fi":    "Finnish",
    "fj":    "Fijian",
    "fo":    "Faeroese",
    "fr":    "French",
    "fy":    "Frisian",
    "ga":    "Irish",
    "gd":    "Gaelic",
    "gl":    "Galician",
    "gn":    "Guarani",
    "gu":    "Gujarati",
    "ha":    "Hausa",
    "he":    "Hebrew",
    "hi":    "Hindi",
    "hr":    "Croatian",
    "hu":    "Hungarian",
    "hy":    "Armenian",
    "ia":    "Interlingua",
    "id":    "Indonesian",
    "ie":    "Interlingue",
    "ik":    "Inupiak",
    "in":    "Indonesian",
    "is":    "Icelandic",
    "it":    "Italian",
    "iw":    "Hebrew",
    "ja":    "Japanese",
    "ji":    "Yiddish",
    "jw":    "Javanese",
    "ka":    "Georgian",
    "kk":    "Kazakh",
    "kl":    "Greenlandic",
    "km":    "Cambodian",
    "kn":    "Kannada",
    "ko":    "Korean",
    "ks":    "Kashmiri",
    "ku":    "Kurdish",
    "ky":    "Kirghiz",
    "kz":    "Kyrgyz",
    "la":    "Latin",
    "ln":    "Lingala",
    "lo":    "Laothian",
    "ls":    "Slovenian",
    "lt":    "Lithuanian",
    "lv":    "Latvian",
    "mg":    "Malagasy",
    "mi":    "Maori",
    "mk":    "FYRO Macedonian",
    "ml":    "Malayalam",
    "mn":    "Mongolian",
    "mo":    "Moldavian",
    "mr":    "Marathi",
    "ms":    "Malay",
    "mt":    "Maltese",
    "my":    "Burmese",
    "na":    "Nauru",
    "ne":    "Nepali (India)",
    "nl":    "Dutch",
    "no":    "Norwegian (Bokmal)",
    "oc":    "Occitan",
    "om":    "(Afan)/Oromoor/Oriya",
    "or":    "Oriya",
    "pa":    "Punjabi",
    "pl":    "Polish",
    "ps":    "Pashto/Pushto",
    "pt":    "Portuguese",
    "qu":    "Quechua",
    "rm":    "Rhaeto-Romanic",
    "rn":    "Kirundi",
    "ro":    "Romanian",
    "ru":    "Russian",
    "rw":    "Kinyarwanda",
    "sa":    "Sanskrit",
    "sb":    "Sorbian",
    "sd":    "Sindhi",
    "sg":    "Sangro",
    "sh":    "Serbo-Croatian",
    "si":    "Singhalese",
    "sk":    "Slovak",
    "sl":    "Slovenian",
    "sm":    "Samoan",
    "sn":    "Shona",
    "so":    "Somali",
    "sq":    "Albanian",
    "sr":    "Serbian",
    "ss":    "Siswati",
    "st":    "Sesotho",
    "su":    "Sundanese",
    "sv":    "Swedish",
    "sw":    "Swahili",
    "sx":    "Sutu",
    "ta":    "Tamil",
    "te":    "Telugu",
    "tg":    "Tajik",
    "th":    "Thai",
    "ti":    "Tigrinya",
    "tk":    "Turkmen",
    "tl":    "Tagalog",
    "tn":    "Tswana",
    "to":    "Tonga",
    "tr":    "Turkish",
    "ts":    "Tsonga",
    "tt":    "Tatar",
    "tw":    "Twi",
    "uk":    "Ukrainian",
    "ur":    "Urdu",
    "us":    "English",
    "uz":    "Uzbek",
    "vi":    "Vietnamese",
    "vo":    "Volapuk",
    "wo":    "Wolof",
    "xh":    "Xhosa",
    "yi":    "Yiddish",
    "yo":    "Yoruba",
    "zh":    "Chinese",
    "zu":    "Zulu"
}