import Head from 'next/head'
import Image from 'next/image'
import Layout from "../components/Layout/Layout"
import { useRouter } from 'next/router'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useMoralis } from "react-moralis"


export default function Home() {

  const router = useRouter()
  const { t } = useTranslation('common')

  const { account } = useMoralis()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center">

        <h1 className="mt-10 text-center text-6xl font-medium tracking-wide">
          {t("h1")} <span className="bg-gradient-to-tr from-teal-500 to-sky-500 bg-clip-text text-transparent">OakSquare</span>
        </h1>

        <p className="mt-20">{t('welcome')}</p>

        <p>{account}</p>



      </div>

    </>
  )
}


Home.getLayout = function getLayout(page) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}

export const getStaticProps = async ({ locale }) => ({
  props: {
    ...await serverSideTranslations(locale, ['common', 'navigation', 'footer']),
  },
})