import Head from 'next/head'
import Image from 'next/image'
import Layout from "../components/Layout/Layout"
import { useRouter } from 'next/router'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useMoralis } from "react-moralis"
import Link from 'next/link';
import FuncWriteCreateNewNftBook from "../components/Functions/Factory/FuncWriteCreateNewNftBook"
import FuncReadContractFactory from "../components/Functions/Factory/FuncReadContractFactory"
import FuncReadNft from "../components/Functions/NFTs/FuncReadNft"
import { useRef } from "react"

export default function Home() {

  const router = useRouter()
  const { t } = useTranslation('common')
  const { account } = useMoralis()
  
  const textRef = useRef("")
  const formatTo1155 = () => {
    // 1-S 2-D 3-N 4-T 5-R 6-Y 7-L 8-C Other-9
    let str = textRef.current.value
    console.log(str);
    let result
    let regex = /[^0-9a-fsdntryls]/g
    let hardCore = str.split(" ").join("").toLowerCase().slice(0,63)
    console.log("check 1:", hardCore);
    hardCore = hardCore
      .replaceAll("s","1")
      .replaceAll("d","2")
      .replaceAll("n","3")
      .replaceAll("t","4")
      .replaceAll("r","5")
      .replaceAll("y","6")
      .replaceAll("l","7")
      .replaceAll("s","8")
      .replaceAll(regex, "9")
    console.log("check 2:", hardCore);
    let missingCount = 63 - hardCore.length
    console.log("missing count:", missingCount);
    let missingZero = []
    Array.from(Array(missingCount).keys()).map(() => missingZero.push("0"))
    console.log("missing 0:", missingZero);
    result = `0${missingZero.join("")}${hardCore}.json`
    console.log(result);
  }

  const test = async () => {
    const response = await fetch(`${router.basePath}/api/hello/`, {
      method: "POST",
      
    })
    const data = await response.json()
    console.log(data);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto w-full max-w-7xl flex flex-col items-center">

        <h1 className="mt-10 text-center text-6xl font-medium tracking-wide">
          {t("h1")} <span className="bg-gradient-to-tr from-teal-500 to-sky-500 bg-clip-text text-transparent">PubliRare</span>
        </h1>

        <p className="mt-20">{t('welcome')}</p>

        <p>{account}</p>

        <Link href="/security/team-space">
          <a className="mt-4 text-teal-700 underline">Team Space</a>
        </Link>

        <div className="mt-10 flex flex-wrap">
          <div className="m-2">
            <FuncWriteCreateNewNftBook
              name="createNewNFTBook"
              amount={500}
              maxCopies={500}
              royaltyFeesInBips={1000}
              uri="https://gateway.pinata.cloud/ipfs/QmVLhnokCzD4VZeqghc5EhtYSP5YFNtGPPmXmkJkKuMZdn/"
              contractURI="https://gateway.pinata.cloud/ipfs/QmaQvPj7WDJSJHZjz6fph9UAVEXs924XQCEh77t7ACGDXs/"
              collectionName="One Piece Serie"
              className="relative m-3 inline-flex justify-center items-center px-7 py-3.5 min-w-[160px] h-16 border border-transparent rounded-2xl bg-sky-400 text-2xl text-white font-bold tracking-wide hover:bg-sky-500"
            >
              Mint
            </FuncWriteCreateNewNftBook>
          </div>
          <div className="m-2">
            <FuncReadContractFactory
              name="getContractAddress"
              contractID={0}
              className="relative m-3 inline-flex justify-center items-center px-7 py-3.5 min-w-[160px] h-16 border border-transparent rounded-2xl bg-purple-400 text-2xl text-white font-bold tracking-wide hover:bg-purple-500">
              Get contract address
            </FuncReadContractFactory>
          </div>
          
          <div className="m-2">
            <FuncReadNft
              name="uri"
              addr="0x343C5cDbB195869DF164935d978F498a9fF52F35"
              contractID={0}
              className="relative m-3 inline-flex justify-center items-center px-7 py-3.5 min-w-[160px] h-16 border border-transparent rounded-2xl bg-green-400 text-2xl text-white font-bold tracking-wide hover:bg-green-500">
              Get URI
            </FuncReadNft>
          </div>
        </div>

        <input type="text" ref={textRef} name="" id="" />
        <button onClick={test} className="bg-pink-400 text-white">format</button>

      </div>

    </>
  )
}


//! ====================== LOADING =============================================================================================
Home.getLayout = function getLayout(page) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}


//! ====================== LOAD TRANSLATIONS =============================================================================================
export const getStaticProps = async ({ locale }) => ({
  props: {
    ...await serverSideTranslations(locale, ['common', 'navigation', 'footer']),
  },
})